---

# This play is designed for SaaS Deployments that already have a Root CA configured
# Create a folder in the playbook directory called "ejbcaCaCerts" and place the Root CA crt inside
# Update the root_ca variable in the deploy_vars with the certificate basename

- hosts: prod
  pre_tasks:
    - include_vars:
        dir: deployment_info/insulet_eu_deployment
  vars:
    - add_certification_authorities: "{{ sub_add_certification_authorities }}"
    - sub_node_play: true
    - prep_config_dump: true
    - saas_context: arn:aws:eks:eu-north-1:645750012002:cluster/production-eu-north-1
    - domain_name: eu-prod-omnipodcloud
  roles:
    - ansible-saas-deployment
    - ansible-ejbca-deploy-pki-ext-signed-sub-1

- hosts: prod
  pre_tasks:
    - include_vars:
        dir: deployment_info/insulet_eu_deployment
  vars:
    - add_certification_authorities: "{{ sub_add_certification_authorities }}"
    - root_node_play: true
    - create_end_entities: true
    - saas_context: arn:aws:eks:us-east-2:645750012002:cluster/production-us-east-2
    - domain_name: prod-omnipodcloud
  roles:
    - ansible-saas-deployment
