---

- name: Convert DER encoded CSR to PEM
  command: openssl req -inform DER -outform PEM -in {{ ejbca_csr_dir_output }}/{{ item.caname }}_csr.der -out {{ ejbca_csr_dir_output }}/{{ item.caname }}.csr
  become: no
  loop: "{{ add_certification_authorities }}"
  loop_control:
    label: "{{ item.caname }}"
  no_log: true